services:
  drone-gym:
    # image: scrl # for quick test, but needs to be fixed
    image: 182863709418.dkr.ecr.us-east-2.amazonaws.com/umpire-assist:v1.0.4
    # image: drone-image:test
    runtime: nvidia
    network_mode: host
    container_name: drone-image-dev
    stdin_open: true
    tty: true
    volumes:
      # CODE
      - /home/jansel/Documents/research/drone_gym:/app
    environment:
      - DISPLAY=${DISPLAY}

